### ISSUE TITLE
Architecture issue in swift 4.0 

### ISSUE THREAD

**Issue by keval94** [DFTinc/onyx-camera-cocoapod#1]
i am trying to add in swift and its shows me this error  
i am using x-code 10 and swift 4.0
![screen shot 2018-11-23 at 2 29 33 pm](https://user-images.githubusercontent.com/45285122/48936013-91989f00-ef2f-11e8-94ee-ced0cf35197f.png)

**Comment by keval94** [comment]
Please provide swift demo

**Comment by ahsanghauri** [comment]
same issue with me any solutions?

**Comment by RussianRoulette84** [comment]
try disabling "bitcode"
